/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package p1.t7.vista.garciajimenezfrancisco;

import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import org.milaifontanals.esport.interficiePersistencia.GestorBDEsportException;
import org.milaifontanals.esport.interficiePersistencia.IGestorBDEsport;
import org.milaifontanals.esport.model.*;

/**
 *
 * @author fran_
 */
public class afegirEquip extends javax.swing.JFrame {

    IGestorBDEsport bd = null;
    Equip equipParam = null;
    Integer idEquipEditar = null;
    String temporadaParam = null;
    
    public afegirEquip(IGestorBDEsport dades, Equip equipParam) {
        initComponents();
        this.bd = dades;
        carregarTemporades();
        carregarCategories();

        if (equipParam != null) {
            System.out.println("Equip seleccionat a editar: " + equipParam);
            this.idEquipEditar = equipParam.getId();
            String nomEquip = equipParam.getNom().substring(0, equipParam.getNom().length() - 6);
            tfNom.setText(nomEquip);
            cbTemporada.setSelectedItem(String.valueOf(equipParam.getAny_temporada()));
            cbTipus.setSelectedItem(String.valueOf(equipParam.getTipus()));
            
            try {
                Categoria categoria = bd.getCategoriaById(equipParam.getId_categoria());
                cbCategoria.setSelectedItem(categoria.getNom());
            } catch (GestorBDEsportException e) {
                lbInfo.setForeground(Color.RED);
                lbInfo.setText("Error al obtener la categoría: " + e.getMessage());
            }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfNom = new javax.swing.JTextField();
        cbTipus = new javax.swing.JComboBox<>();
        cbTemporada = new javax.swing.JComboBox<>();
        cbCategoria = new javax.swing.JComboBox<>();
        jToggleButton5 = new javax.swing.JToggleButton();
        jLabel5 = new javax.swing.JLabel();
        btAfegirEquip = new javax.swing.JToggleButton();
        lbInfo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(238, 238, 238));
        jPanel1.setFocusable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Tipus");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Nom");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Any temporada");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Categoria");

        cbTipus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "H", "D", "M" }));

        cbTemporada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jToggleButton5.setBackground(new java.awt.Color(204, 204, 204));
        jToggleButton5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jToggleButton5.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton5.setText("<<");
        jToggleButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton5ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel5.setText("Gestor de equips");

        btAfegirEquip.setBackground(new java.awt.Color(255, 204, 153));
        btAfegirEquip.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btAfegirEquip.setForeground(new java.awt.Color(102, 102, 102));
        btAfegirEquip.setText("Desar");
        btAfegirEquip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAfegirEquipActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1))
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(btAfegirEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jToggleButton5)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cbTemporada, javax.swing.GroupLayout.Alignment.LEADING, 0, 200, Short.MAX_VALUE)
                            .addComponent(tfNom, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbTipus, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 63, Short.MAX_VALUE)
                .addComponent(lbInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jToggleButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                        .addGap(64, 64, 64))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbTipus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbTemporada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(btAfegirEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(lbInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void carregarTemporades() {
        try {
            List<Temporada> lTemp = bd.getTemporades(); 

            cbTemporada.removeAllItems();

            for (Temporada t : lTemp) {
                cbTemporada.addItem(String.valueOf(t.getAny()));
            }
        } catch (GestorBDEsportException e) {
            System.out.println("Error al carregar les temporades: " + e.getMessage());
        }
    }
    
    
    private void carregarCategories() {
        try {
            List<Categoria> lCat = bd.getCategories(); 

            cbCategoria.removeAllItems();

            for (Categoria c : lCat) {
                cbCategoria.addItem(c.getNom());
            }
        } catch (GestorBDEsportException e) {
            System.out.println("Error al carregar les categories: " + e.getMessage());
        }
    }

    private void btAfegirEquipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAfegirEquipActionPerformed
        String nom = tfNom.getText();  
        String tipusString = (String) cbTipus.getSelectedItem();
        char tipus = tipusString.charAt(0); 
        int temporada = Integer.parseInt((String) cbTemporada.getSelectedItem()); 
        String categoriaNom = (String) cbCategoria.getSelectedItem(); 
        
        temporadaParam = String.valueOf(temporada);
        
        try {  
            int categoria = bd.getIdCategoriaByNom(categoriaNom);
            
            if (idEquipEditar == null) {
                try {
                    Equip equip = new Equip(nom, tipus, temporada, categoria);
                    bd.addEquip(equip);
                    System.out.println("Equip afegit: " + equip);
                    lbInfo.setForeground(Color.BLUE);
                    lbInfo.setText("Equip afegit.");
                } catch (GestorBDEsportException e) {
                    System.out.println("Error en insertar l'equip: " + e.getMessage());
                    lbInfo.setForeground(Color.RED);
                    lbInfo.setText("Error en inserir l'equip.\n\nMotiu:\n\n" + e.getMessage());
                }
            } else {
                try {
                    Equip equip = new Equip(nom, tipus, temporada, categoria);
                    bd.editEquip(idEquipEditar, equip);
                    System.out.println("Equip editat."+equip);
                    lbInfo.setForeground(Color.BLUE);
                    lbInfo.setText("Equip editat: ");
                } catch (GestorBDEsportException e) {
                    System.out.println("Error en editar l'equip: " + e.getMessage());
                    lbInfo.setForeground(Color.RED);
                    lbInfo.setText("Error en editar l'equip.\n\nMotiu:\n\n" + e.getMessage());
                }
            }

        } catch (GestorBDEsportException e) {
            System.out.println("Error en l'operació de l'equip: " + e.getMessage());
            lbInfo.setForeground(Color.RED);
            lbInfo.setText("Error en l'operació de l'equip.\n\nMotiu:\n\n" + e.getMessage());
        }
    }//GEN-LAST:event_btAfegirEquipActionPerformed

    private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton5ActionPerformed
        if(temporadaParam == null){
            GestioEquips gt = new GestioEquips(this.bd, "2024");
            gt.setVisible(true);
            this.dispose();
        } else {
            GestioEquips gt = new GestioEquips(this.bd, temporadaParam);
            gt.setVisible(true);
            this.dispose();
        }     
        
    }//GEN-LAST:event_jToggleButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(afegirEquip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(afegirEquip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(afegirEquip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(afegirEquip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new afegirEquip().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btAfegirEquip;
    private javax.swing.JComboBox<String> cbCategoria;
    private javax.swing.JComboBox<String> cbTemporada;
    private javax.swing.JComboBox<String> cbTipus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JLabel lbInfo;
    private javax.swing.JTextField tfNom;
    // End of variables declaration//GEN-END:variables
}
