/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package p1.t7.vista.garciajimenezfrancisco;

import java.awt.Color;
import java.awt.Component;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import org.milaifontanals.esport.interficiePersistencia.IGestorBDEsport;
import org.milaifontanals.esport.interficiePersistencia.GestorBDEsportException;
import org.milaifontanals.esport.model.*;

/**
 *
 * @author fran_
 */
public class fitxarJugadorsEquip extends javax.swing.JFrame {

    IGestorBDEsport bd = null;
    Integer idEquip = null;
    public fitxarJugadorsEquip(IGestorBDEsport dades, int idEquip) throws GestorBDEsportException {
        initComponents();
        pnTitular.setVisible(false);
        
        sgDisponibles.getColumnModel().getColumn(0).setMinWidth(0);  
        sgDisponibles.getColumnModel().getColumn(0).setMaxWidth(0);  
        sgDisponibles.getColumnModel().getColumn(0).setWidth(0);    
        sgDisponibles.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(0);
        
        sgInscrits.getColumnModel().getColumn(0).setMinWidth(0);  
        sgInscrits.getColumnModel().getColumn(0).setMaxWidth(0);  
        sgInscrits.getColumnModel().getColumn(0).setWidth(0);    
        sgInscrits.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(0);
        
        this.bd = dades;
        this.idEquip = idEquip;
        
        String nomEquip = bd.getNomEquipById(idEquip);
        lbTitle.setText(nomEquip);
        
        carregarJugadorsEquip();
        carregarJugadorsDisponibles();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitle = new javax.swing.JLabel();
        jToggleButton5 = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        sgInscrits = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        sgDisponibles = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        cbTemporadaInscrits = new javax.swing.JComboBox<>();
        bFilte = new javax.swing.JButton();
        tfInscrits = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cbTemporadaDisponibles = new javax.swing.JComboBox<>();
        bFilte1 = new javax.swing.JButton();
        tfDisponibles = new javax.swing.JTextField();
        btDelJug = new javax.swing.JToggleButton();
        btAddJug = new javax.swing.JToggleButton();
        pnTitular = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btNoTitular = new javax.swing.JButton();
        btSiTitular = new javax.swing.JButton();
        lbInfo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lbTitle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbTitle.setText("Fixa de equip");

        jToggleButton5.setBackground(new java.awt.Color(204, 204, 204));
        jToggleButton5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jToggleButton5.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton5.setText("<<");
        jToggleButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton5ActionPerformed(evt);
            }
        });

        sgInscrits.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "NIF Jugador", "Nom cognom", "Titular"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(sgInscrits);

        jLabel1.setText("Jugadors inscrits");

        sgDisponibles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "NIF Jugador", "Nom cognom", "Any fi revisió medica"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(sgDisponibles);

        jLabel2.setText("Jugadors disponibles");

        jPanel1.setBackground(new java.awt.Color(255, 204, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cbTemporadaInscrits.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nom", "NIF", "Categoria" }));
        cbTemporadaInscrits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTemporadaInscritsActionPerformed(evt);
            }
        });

        bFilte.setBackground(new java.awt.Color(153, 153, 153));
        bFilte.setForeground(new java.awt.Color(255, 255, 255));
        bFilte.setText("Mostra");
        bFilte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFilteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(cbTemporadaInscrits, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfInscrits, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bFilte)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTemporadaInscrits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bFilte)
                    .addComponent(tfInscrits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel3.setText("Filtrar");

        jLabel4.setText("Filtrar");

        jPanel2.setBackground(new java.awt.Color(255, 204, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cbTemporadaDisponibles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nom", "NIF", "Categoria" }));
        cbTemporadaDisponibles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTemporadaDisponiblesActionPerformed(evt);
            }
        });

        bFilte1.setBackground(new java.awt.Color(153, 153, 153));
        bFilte1.setForeground(new java.awt.Color(255, 255, 255));
        bFilte1.setText("Mostra");
        bFilte1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFilte1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbTemporadaDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(tfDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bFilte1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTemporadaDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bFilte1)
                    .addComponent(tfDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btDelJug.setBackground(new java.awt.Color(255, 0, 0));
        btDelJug.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btDelJug.setForeground(new java.awt.Color(255, 255, 255));
        btDelJug.setText(">");
        btDelJug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDelJugActionPerformed(evt);
            }
        });

        btAddJug.setBackground(new java.awt.Color(51, 153, 0));
        btAddJug.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btAddJug.setForeground(new java.awt.Color(255, 255, 255));
        btAddJug.setText("<");
        btAddJug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddJugActionPerformed(evt);
            }
        });

        pnTitular.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setText("Vols que el jugador sigui titular?");

        btNoTitular.setText("No");
        btNoTitular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNoTitularActionPerformed(evt);
            }
        });

        btSiTitular.setText("Si");
        btSiTitular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSiTitularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnTitularLayout = new javax.swing.GroupLayout(pnTitular);
        pnTitular.setLayout(pnTitularLayout);
        pnTitularLayout.setHorizontalGroup(
            pnTitularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTitularLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(pnTitularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addGroup(pnTitularLayout.createSequentialGroup()
                        .addComponent(btSiTitular)
                        .addGap(32, 32, 32)
                        .addComponent(btNoTitular)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        pnTitularLayout.setVerticalGroup(
            pnTitularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTitularLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(pnTitularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSiTitular)
                    .addComponent(btNoTitular))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btAddJug, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                            .addComponent(btDelJug, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(109, 109, 109))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(469, 469, 469))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jToggleButton5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(420, 420, 420)
                        .addComponent(pnTitular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(242, 242, 242)
                .addComponent(lbInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jToggleButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(lbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnTitular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btAddJug, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(btDelJug, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50)
                .addComponent(lbInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
private void carregarJugadorsEquip() throws GestorBDEsportException {
    List<Jugador> jugadors = bd.getJugadorsEquip(idEquip);

    DefaultTableModel model = (DefaultTableModel) sgInscrits.getModel();
    
    model.setRowCount(0);

    for (Jugador j : jugadors) {
        Integer id = j.getId();
        String nomCognoms = j.getNom() + " " + j.getCognoms();
        String nif = j.getIdlegal();
        int esTitular = bd.verificaTitular(idEquip, j.getId());
        Boolean bTitular = null;
        if (esTitular == 1) {
            bTitular = true;
        } else { 
            bTitular = false;
        }
        model.addRow(new Object[]{id, nif, nomCognoms, bTitular});
    }
}

private void carregarJugadorsDisponibles() throws GestorBDEsportException {
    List<Jugador> jugadors = bd.getJugadorsEquipDisponibles(idEquip);

    DefaultTableModel model = (DefaultTableModel) sgDisponibles.getModel();
    
    model.setRowCount(0);

    for (Jugador j : jugadors) {
        Integer id = j.getId();
        String nomCognoms = j.getNom() + " " + j.getCognoms();
        String nif = j.getIdlegal();
        Integer any_revisio = j.getAny_fi_revisio_medica();
        model.addRow(new Object[]{id,nif, nomCognoms, any_revisio});
    }
}
private void setComponentsVisible(boolean visible) {   
    jPanel1.setVisible(visible);
    jPanel2.setVisible(visible);
    jLabel1.setVisible(visible);
    jLabel2.setVisible(visible);
    jLabel3.setVisible(visible);
    jLabel4.setVisible(visible);
    btAddJug.setVisible(visible);
    btDelJug.setVisible(visible);
    sgInscrits.setVisible(visible);
    sgDisponibles.setVisible(visible);
}
private void afegirJugadorAlEquip(boolean titular) throws GestorBDEsportException {
    int filaSeleccionada = sgDisponibles.getSelectedRow();
    if (filaSeleccionada != -1) {
        int idJugador = Integer.parseInt(sgDisponibles.getValueAt(filaSeleccionada, 0).toString());
        bd.addJugadorEquip(idJugador, idEquip, titular ? 1 : 0);
    }
}




    private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton5ActionPerformed
        GestioEquips gt = new GestioEquips(this.bd, "2024");
        gt.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jToggleButton5ActionPerformed

    private void cbTemporadaInscritsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTemporadaInscritsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTemporadaInscritsActionPerformed

    private void bFilteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFilteActionPerformed

    }//GEN-LAST:event_bFilteActionPerformed

    private void cbTemporadaDisponiblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTemporadaDisponiblesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTemporadaDisponiblesActionPerformed

    private void bFilte1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFilte1ActionPerformed

    }//GEN-LAST:event_bFilte1ActionPerformed

    private void btDelJugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDelJugActionPerformed
        int selectedRow = sgInscrits.getSelectedRow();
        if (selectedRow == -1) {
            lbInfo.setForeground(Color.RED);
            lbInfo.setText("Selecciona un jugador a eliminar.");
            return;
        }

        int idJugador = (int) sgInscrits.getValueAt(selectedRow, 0);

        try {
            bd.delJugadorEquip(idJugador, idEquip);
            carregarJugadorsEquip();
            carregarJugadorsDisponibles();
            lbInfo.setForeground(Color.BLUE);
            lbInfo.setText("Jugador eliminat.");
            
        } catch (GestorBDEsportException ex) {
            lbInfo.setForeground(Color.RED);
            lbInfo.setText(ex.getMessage());
        }
    }//GEN-LAST:event_btDelJugActionPerformed

    private void btAddJugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddJugActionPerformed
        int selectedRow = sgDisponibles.getSelectedRow();
    
        if (selectedRow != -1) {
            pnTitular.setVisible(true);
            setComponentsVisible(false);
            btSiTitular.requestFocus();
        } else {
            lbInfo.setForeground(Color.RED);
            lbInfo.setText( "Selecciona un jugador a afegir. ");
        }
    }//GEN-LAST:event_btAddJugActionPerformed

    private void btSiTitularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSiTitularActionPerformed
       pnTitular.setVisible(false);  
       setComponentsVisible(true);   
        try {
            afegirJugadorAlEquip(true);
            carregarJugadorsEquip();
            carregarJugadorsDisponibles();
        } catch (GestorBDEsportException ex) {
            lbInfo.setForeground(Color.RED);
            lbInfo.setText(ex.getMessage());
        }
    }//GEN-LAST:event_btSiTitularActionPerformed

    private void btNoTitularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNoTitularActionPerformed
       pnTitular.setVisible(false);  
       setComponentsVisible(true); 
       try {
            afegirJugadorAlEquip(false);
            carregarJugadorsEquip();
            carregarJugadorsDisponibles();
            lbInfo.setForeground(Color.BLUE);
            lbInfo.setText( "Jugador afegit al equip. ");
        } catch (GestorBDEsportException ex) {
            lbInfo.setForeground(Color.RED);
            lbInfo.setText(ex.getMessage());
        }
    }//GEN-LAST:event_btNoTitularActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bFilte;
    private javax.swing.JButton bFilte1;
    private javax.swing.JToggleButton btAddJug;
    private javax.swing.JToggleButton btDelJug;
    private javax.swing.JButton btNoTitular;
    private javax.swing.JButton btSiTitular;
    private javax.swing.JComboBox<String> cbTemporadaDisponibles;
    private javax.swing.JComboBox<String> cbTemporadaInscrits;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JLabel lbInfo;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JPanel pnTitular;
    private javax.swing.JTable sgDisponibles;
    private javax.swing.JTable sgInscrits;
    private javax.swing.JTextField tfDisponibles;
    private javax.swing.JTextField tfInscrits;
    // End of variables declaration//GEN-END:variables
}
